version: '3'

services:

  postgres:
    container_name: delivery
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: delivery
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:


networks:
  default:
    external:
      name: delivery